name: build 

on:
  pull_request:
    branches:
      - develop 

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.4.16f1
        targetPlatform:
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
    
        # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
          
        # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
            
        #libSDL2 for Wwise integration
      - name: install libSDL2
        run: |
          sudo apt-get install build-essential libasound2-dev
          wget http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
          tar -zxvf SDL2-2.0.3.tar.gz
          cd SDL2-2.0.3
          ./configure
          make
          sudo make install
          sudo ldconfig

            
        # build
      - name: Build project
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_STANDALONE_WIN: 1
          UNITY_EDITOR_WIN: 1
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          allowDirtyBuild: true
          
          # output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
